from src.fs_parser.geometric.operations import (
    AssignVariable,
    BooleanBodies,
    Chamfer,
    CircularPattern,
    Cplane,
    Cpoint,
    DeleteBodies,
    Extrude,
    Fillet,
    Hole,
    Loft,
    Mirror,
    Revolve,
    Shell,
    Sweep,
    Transform,
)

# Maps a FeatureScript op keyword to its reducer instance (None = recognised but ignored).
SUPPORTED_GEOMETRIC_OPS = {
    'assignVariable': AssignVariable(),
    'extrude': Extrude(),
    'cPlane': Cplane(),
    'cPoint': Cpoint(),
    'chamfer': Chamfer(),
    'fillet': Fillet(),
    'revolve': Revolve(),
    'loft': Loft(),
    'mirror': Mirror(),
    'booleanBodies': BooleanBodies(),
    'hole': Hole(),
    'shell': Shell(),
    'sweep': Sweep(),
    'transform': Transform(),
    'deleteBodies': DeleteBodies(),
    'circularPattern': CircularPattern(),
    'mateConnector': None,
}
